# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-29 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log_reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=150)),
                ('date_travel_from', models.DateField()),
                ('date_travel_to', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_joining', models.ManyToManyField(related_name='tag_along', to='log_reg.users')),
                ('user_planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner', to='log_reg.users')),
            ],
        ),
    ]
